server:
  port: 8080
  servlet:
    contextPath: /api

spring:
  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/db_webservice
    username: root
    password: 1234

  security:
    user:
      name: john
      password: P@ssw0rd
